// Generated by divisi security | Optimized by EASE-OS Enterprise Software Engineer 2026

/**
 * KONFIGURASI SCHEMA DATABASE - SECURED VIA PROPERTIES SERVICE (EOS-PATTERN-033)
 */
const scriptProperties = PropertiesService.getScriptProperties();
const EMAIL_RECIPIENTS = scriptProperties.getProperty('EMAIL_RECIPIENTS');
const APP_LINK = scriptProperties.getProperty('APP_LINK');

// Validasi preventif runtime environment initialization
if (!EMAIL_RECIPIENTS || !APP_LINK) {
  Logger.log("CRITICAL ERROR: Script Properties 'EMAIL_RECIPIENTS' atau 'APP_LINK' belum dikonfigurasi di Google Apps Script!");
}

function getDbSchema() {
  return [
    { name: 'MASTER_USER', header: ['Username', 'Password', 'Nama', 'Role', 'WK_Access'] },
    { name: 'MASTER_WILAYAH_KERJA', header: ['ID', 'Nama_WK', 'BUJP_NAME', 'LAT', 'LNG', 'PERSONNEL_COUNT', 'CONTRACT_END_DATE'] },
    { name: 'MASTER_BUJP', header: ['ID', 'Nama_BUJP'] },
    { name: 'MASTER_BUJP_WK', header: ['Nama_BUJP', 'Nama_WK'] },
    { name: 'MASTER_ITEM_ANGGARAN', header: ['ID', 'Nama_Item'] },
    { name: 'MASTER_PILIHAN_ANGGARAN', header: ['ID', 'Nama_Pilihan'] },
    { name: 'MASTER_JENIS_TRANSAKSI', header: ['ID', 'Nama_Label', 'Kategori_Sistem'] },
    { name: 'MASTER_ANGGARAN', header: ['ID', 'WK', 'BUJP', 'Deskripsi', 'Item', 'Pagu'] },
    { name: 'TRANSAKSI_REALISASI', header: ['ID', 'Tanggal', 'WK', 'BUJP', 'Item', 'Pilihan_Anggaran', 'Jumlah', 'Keterangan', 'Input_By', 'Evidence'] },
    { name: 'TRANSAKSI_INVOICE_BUJP', header: ['ID', 'Tanggal', 'WK', 'BUJP', 'Item', 'Pilihan_Anggaran', 'Jumlah', 'No_Invoice', 'Input_By', 'Evidence'] },
    { name: 'TRANSAKSI_STAKEHOLDER', header: ['ID', 'Tanggal', 'WK', 'BUJP', 'Item', 'Pilihan_Anggaran', 'Jumlah', 'Keterangan', 'Input_By', 'Evidence'] },
    { name: 'LOG_ACTIVITY', header: ['Timestamp', 'User', 'Action', 'Detail'] }
  ];
}

/**
 * SETUP DATABASE: Inisialisasi Sheet dan Kolom
 */
function setupDatabase() {
  const ss = SpreadsheetApp.getActiveSpreadsheet();
  const sheets = getDbSchema();

  sheets.forEach(sh => {
    let sheet = ss.getSheetByName(sh.name);
    if (!sheet) {
      sheet = ss.insertSheet(sh.name);
      sheet.getRange(1, 1, 1, sh.header.length).setValues([sh.header]).setFontWeight('bold').setBackground('#d9ead3');
    } else {
      const lastCol = sheet.getLastColumn();
      if (lastCol > 0) {
        const headers = sheet.getRange(1, 1, 1, lastCol).getValues()[0];
        if (sh.name.includes('TRANSAKSI') && !headers.includes('Evidence')) {
          sheet.getRange(1, lastCol + 1).setValue('Evidence').setFontWeight('bold').setBackground('#d9ead3');
        }
      }
    }
  });

  // Default Data jika kosong - SECURED VIA DEFINTIVE SHA-256 HASH SEEDING
  const userSheet = ss.getSheetByName('MASTER_USER');
  if (userSheet.getLastRow() === 1) {
    const secureAdminHash = "5d69352e80556f082e66b450702c2e5b706c9bc9e5c46b5a3717dfb11961e626";
    userSheet.appendRow(['admin', secureAdminHash, 'Administrator', 'ADMIN', 'ALL']);
  }

  const jenisSheet = ss.getSheetByName('MASTER_JENIS_TRANSAKSI');
  if (jenisSheet.getLastRow() === 1) {
    jenisSheet.appendRow(['1', 'Payment Request', 'internal']);
    jenisSheet.appendRow(['2', 'Expense Claim', 'internal']);
    jenisSheet.appendRow(['3', 'Invoice BUJP', 'invoice']);
    jenisSheet.appendRow(['4', 'Invoice Stakeholder', 'stakeholder']);
  }

  return "Database Siap & Terupdate!";
}

// -------------------------------------------------------------------------
// FUNGSI UTAMA: doGet (Mendukung Web App & Jalur REST API Engine)
// -------------------------------------------------------------------------
function doGet(e) {
  if (e && e.parameter && e.parameter.action === "getAppData") {
    // SECURITY FALLBACK SYNC: Cegah alokasi data terpotong menjadi 0 akibat delay handshake klien
    const clientUsername = e.parameter.username || "";
    let secureRole = e.parameter.role;
    let secureWkAccess = e.parameter.wkAccess;

    if (clientUsername) {
      const serverCheck = verifyServerSideRole(clientUsername);
      if (serverCheck.active) {
        secureRole = serverCheck.user.role;
        secureWkAccess = serverCheck.user.wkAccess;
      }
    }

    var responseData = getAppData(secureRole, secureWkAccess);
    return ContentService.createTextOutput(JSON.stringify(responseData))
        .setMimeType(ContentService.MimeType.JSON);
  }

  return HtmlService.createTemplateFromFile('Index')
    .evaluate()
    .setTitle('Budget Monitoring V3.1')
    .setXFrameOptionsMode(HtmlService.XFrameOptionsMode.ALLOWALL)
    .addMetaTag('viewport', 'width=device-width, initial-scale=1');
}

// -------------------------------------------------------------------------
// API PIPELINE: Gerbang Tunggal Pemrosesan Mutasi Data POST (Vercel Polyfill Ready)
// -------------------------------------------------------------------------
function doPost(e) {
  try {
    var params = JSON.parse(e.postData.contents);
    var action = params.action;
    var data = params.data;
    var result;

    if (action === "loginUser") {
      result = loginUser(data.form);
    } else {
      // VALIDATION LAYER SERVER-SIDE: Ambil otoritas hak akses riil langsung dari DB Master
      const serverUserCheck = verifyServerSideRole(data.userData ? data.userData.username : '');
      if (!serverUserCheck.active) {
        return ContentService.createTextOutput(JSON.stringify({ success: false, message: "Akses Ditolak: Sesi Otorisasi Tidak Valid!" }))
            .setMimeType(ContentService.MimeType.JSON);
      }
      
      const secureUserData = serverUserCheck.user;

      if (action === "saveMasterPagu") {
        result = saveMasterPagu(data.payload, secureUserData);
      } else if (action === "deleteMasterPagu") {
        result = deleteMasterPagu(data.id, secureUserData);
      } else if (action === "saveTransaction") {
        result = saveTransaction(data.type, data.payload, secureUserData);
      } else if (action === "updateTransaction") {
        result = updateTransaction(data.id, data.sType, data.payload, secureUserData);
      } else if (action === "deleteData") {
        result = deleteData(data.id, data.sType, secureUserData);
      } else if (action === "updateUserProfile") {
        result = updateUserProfile(data.form);
      }
    }

    return ContentService.createTextOutput(JSON.stringify({ success: true, result: result }))
        .setMimeType(ContentService.MimeType.JSON);
  } catch (err) {
    return ContentService.createTextOutput(JSON.stringify({ success: false, message: err.toString() }))
        .setMimeType(ContentService.MimeType.JSON);
  }
}

/**
 * AUTH SYSTEM
 */
function loginUser(form) {
  try {
    const ss = SpreadsheetApp.getActiveSpreadsheet();
    const sheet = ss.getSheetByName('MASTER_USER');
    const data = sheet.getDataRange().getValues();
    const uInput = String(form.username).trim().toLowerCase();
    const pInput = String(form.password).trim();
    
    const hashedInput = computeSHA256(pInput);

    for (let i = 1; i < data.length; i++) {
      const dbUsername = String(data[i][0]).toLowerCase();
      const dbPassword = String(data[i][1]);

      const isPasswordValid = (dbPassword.length === 64) ? (dbPassword === hashedInput) : (dbPassword === pInput);

      if (dbUsername === uInput && isPasswordValid) {
        if (dbPassword.length !== 64) {
          sheet.getRange(i + 1, 2).setValue(hashedInput);
          ss.getSheetByName('LOG_ACTIVITY').appendRow([new Date(), uInput, "Migration", "Password auto-hashed to SHA-256 for security compliance"]);
        }
        
        ss.getSheetByName('LOG_ACTIVITY').appendRow([new Date(), uInput, "Login Success", "User logged into Budget Monitoring Engine"]);
        return { success: true, user: { username: data[i][0], nama: data[i][2], role: data[i][3], wkAccess: data[i][4] }};
      }
    }
    
    ss.getSheetByName('LOG_ACTIVITY').appendRow([new Date(), uInput, "Login Failed", "Unauthorized access attempt with invalid password"]);
    return { success: false, message: 'Username atau Password salah!' };
  } catch (e) { return { success: false, message: e.toString() }; }
}

/**
 * HELPER COMPUTE SHA-256 CRYPTO ENGINE
 */
function computeSHA256(input) {
  const rawHash = Utilities.computeDigest(Utilities.DigestAlgorithm.SHA_256, input, Utilities.Charset.UTF_8);
  let output = "";
  for (let i = 0; i < rawHash.length; i++) {
    let byteValue = rawHash[i];
    if (byteValue < 0) byteValue += 256;
    let byteString = byteValue.toString(16);
    if (byteString.length == 1) byteString = "0" + byteString;
    output += byteString;
  }
  return output;
}

function getAppData(role, wkAccess) {
  const ss = SpreadsheetApp.getActiveSpreadsheet();
  const getS = (name) => cleanData(ss.getSheetByName(name).getDataRange().getValues());
  
  return {
    masterWK: getS('MASTER_WILAYAH_KERJA'),
    masterBUJP: getS('MASTER_BUJP'),
    masterJenisTrx: getS('MASTER_JENIS_TRANSAKSI'),
    masterPilihan: getS('MASTER_PILIHAN_ANGGARAN'),
    pagu: filterByRole(getS('MASTER_ANGGARAN'), role, wkAccess),
    realisasiInternal: filterByRole(getS('TRANSAKSI_REALISASI'), role, wkAccess),
    realisasiInvoice: filterByRole(getS('TRANSAKSI_INVOICE_BUJP'), role, wkAccess),
    realisasiStakeholder: filterByRole(getS('TRANSAKSI_STAKEHOLDER'), role, wkAccess)
  };
}

/**
 * CRUD: SIMPAN MASTER PAGU
 */
function saveMasterPagu(payload, userData) {
  if (userData.role !== 'ADMIN') return { success: false, message: "Akses Ditolak" };
  const lock = LockService.getScriptLock();
  try {
    lock.waitLock(30000);
    const ss = SpreadsheetApp.getActiveSpreadsheet();
    const sheet = ss.getSheetByName('MASTER_ANGGARAN');
    const headers = sheet.getRange(1, 1, 1, sheet.getLastColumn()).getValues()[0];
    
    const newRow = headers.map(h => {
      if (h === 'ID') return "PG" + Date.now();
      if (h === 'Pagu') return parseSheetNumber(payload.Pagu);
      return payload[h] || "";
    });

    sheet.appendRow(newRow);
    return { success: true };
  } catch (e) { return { success: false, message: e.toString() }; } finally { lock.releaseLock(); }
}

/**
 * CRUD: DELETE MASTER PAGU
 */
function deleteMasterPagu(id, userData) {
  if (userData.role !== 'ADMIN') return { success: false, message: "Akses Ditolak" };
  try {
    const ss = SpreadsheetApp.getActiveSpreadsheet();
    const sheet = ss.getSheetByName('MASTER_ANGGARAN');
    const data = sheet.getDataRange().getValues();
    for (let i = 1; i < data.length; i++) {
      if (String(data[i][0]) === String(id)) {
        sheet.deleteRow(i + 1);
        return { success: true };
      }
    }
    return { success: false, message: "Data tidak ditemukan" };
  } catch (e) { return { success: false, message: e.toString() }; }
}

/**
 * CRUD: SIMPAN TRANSAKSI
 */
function saveTransaction(type, payload, userData) {
  const lock = LockService.getScriptLock();
  try {
    lock.waitLock(30000); 

    let sName = '';
    const typeClean = String(type).toLowerCase();
    if (typeClean === 'internal') sName = 'TRANSAKSI_REALISASI';
    else if (typeClean === 'invoice' || typeClean === 'kontraktual') sName = 'TRANSAKSI_INVOICE_BUJP';
    else if (typeClean === 'stakeholder') sName = 'TRANSAKSI_STAKEHOLDER';
    else throw new Error("Tipe transaksi tidak valid");

    const ss = SpreadsheetApp.getActiveSpreadsheet();
    const sheet = ss.getSheetByName(sName);
    const headers = sheet.getRange(1, 1, 1, sheet.getLastColumn()).getValues()[0];

    let evidenceUrl = "";
    if (payload.fileContent && payload.fileName) {
      const folderName = "Budget_Evidence_2026";
      const folders = DriveApp.getFoldersByName(folderName);
      const folder = folders.hasNext() ? folders.next() : DriveApp.createFolder(folderName);
      const blob = Utilities.newBlob(Utilities.base64Decode(payload.fileContent), payload.mimeType, payload.fileName);
      const file = folder.createFile(blob);
      
      file.setSharing(DriveApp.Access.ANYONE, DriveApp.Permission.NONE); 
      evidenceUrl = file.getUrl();
    }

    const newRow = headers.map(h => {
      if (h === 'ID') return "TX" + Date.now();
      if (h === 'Tanggal') return new Date(payload.tanggal);
      if (h === 'BUJP') return typeClean === 'stakeholder' ? 'NON BUJP' : (payload.BUJP || "");
      if (h === 'No_Invoice') return payload.Keterangan || "";
      if (h === 'Jumlah') return parseSheetNumber(payload.Jumlah);
      if (h === 'Input_By') return userData.username;
      if (h === 'Evidence') return evidenceUrl;
      return payload[h] || "";
    });

    sheet.appendRow(newRow);
    ss.getSheetByName('LOG_ACTIVITY').appendRow([new Date(), userData.username, "Insert " + typeClean, "ID: " + newRow[0]]);
    
    return { success: true };
  } catch (e) { return { success: false, message: e.toString() }; } finally { lock.releaseLock(); }
}

/**
 * CRUD: UPDATE TRANSAKSI
 */
function updateTransaction(id, sType, payload, userData) {
  const lock = LockService.getScriptLock();
  try {
    lock.waitLock(30000);
    let sName = '';
    const typeClean = String(sType).toLowerCase();
    if (typeClean === 'internal') sName = 'TRANSAKSI_REALISASI';
    else if (typeClean === 'invoice') sName = 'TRANSAKSI_INVOICE_BUJP';
    else if (typeClean === 'stakeholder') sName = 'TRANSAKSI_STAKEHOLDER';
    else throw new Error("Tipe sheet tidak valid");

    const ss = SpreadsheetApp.getActiveSpreadsheet();
    const sheet = ss.getSheetByName(sName);
    const data = sheet.getDataRange().getValues();
    const headers = data[0];

    let rowIndex = -1;
    for (let i = 1; i < data.length; i++) {
      if (String(data[i][0]) === String(id)) { rowIndex = i + 1; break; }
    }
    if (rowIndex === -1) throw new Error("Data tidak ditemukan");

    const getCol = (name) => headers.indexOf(name) + 1;
    if (payload.tanggal) sheet.getRange(rowIndex, getCol('Tanggal')).setValue(new Date(payload.tanggal));
    if (payload.Jumlah) sheet.getRange(rowIndex, getCol('Jumlah')).setValue(parseSheetNumber(payload.Jumlah));
    
    const ketColName = headers.includes('No_Invoice') ? 'No_Invoice' : 'Keterangan';
    if (payload.Keterangan) sheet.getRange(rowIndex, getCol(ketColName)).setValue(payload.Keterangan);

    if (payload.fileContent && payload.fileName) {
      const folderName = "Budget_Evidence_2026";
      const folders = DriveApp.getFoldersByName(folderName);
      const folder = folders.hasNext() ? folders.next() : DriveApp.createFolder(folderName);
      const blob = Utilities.newBlob(Utilities.base64Decode(payload.fileContent), payload.mimeType, payload.fileName);
      const file = folder.createFile(blob);
      file.setSharing(DriveApp.Access.ANYONE, DriveApp.Permission.NONE); 
      const evCol = getCol('Evidence');
      if (evCol > 0) sheet.getRange(rowIndex, evCol).setValue(file.getUrl());
    }

    ss.getSheetByName('LOG_ACTIVITY').appendRow([new Date(), userData.username, "Update " + typeClean, "ID Target: " + id]);
    return { success: true };
  } catch (e) { return { success: false, message: e.toString() }; } finally { lock.releaseLock(); }
}

function deleteData(id, sType, userData) {
  try {
    let sName = '';
    const typeClean = String(sType).toLowerCase();
    if (typeClean === 'internal') sName = 'TRANSAKSI_REALISASI';
    else if (typeClean === 'invoice') sName = 'TRANSAKSI_INVOICE_BUJP';
    else if (typeClean === 'stakeholder') sName = 'TRANSAKSI_STAKEHOLDER';
    else throw new Error("Tipe sheet tidak valid");

    const ss = SpreadsheetApp.getActiveSpreadsheet();
    const sheet = ss.getSheetByName(sName);
    const data = sheet.getDataRange().getValues();
    for (let i = 1; i < data.length; i++) {
      if (String(data[i][0]) === String(id)) {
        sheet.deleteRow(i + 1);
        ss.getSheetByName('LOG_ACTIVITY').appendRow([new Date(), userData.username, "Delete " + typeClean, "ID Target: " + id]);
        return { success: true };
      }
    }
    return { success: false, message: "Data tidak ditemukan" };
  } catch (e) { return { success: false, message: e.toString() }; }
}

/**
 * CLEAN DATA & PARSING DESIMAL DAN SEPARATOR (Mencegah Salah Kalkulasi)
 */
function cleanData(values) {
  if (values.length <= 1) return [];
  const headers = values[0];
  return values.slice(1).map(row => {
    const obj = {};
    headers.forEach((h, i) => {
      let v = row[i];
      if (v instanceof Date) {
        v = Utilities.formatDate(v, Session.getScriptTimeZone(), "yyyy-MM-dd");
      } else if (typeof v === 'string') {
        v = v.trim();
      }
      
      if (['Pagu', 'Jumlah', 'PERSONNEL_COUNT'].includes(h)) {
        v = parseSheetNumber(v);
      }
      obj[h] = (v === undefined || v === null) ? "" : v;
    });
    return obj;
  });
}

function parseSheetNumber(val) {
  if (typeof val === 'number') return val;
  if (!val) return 0;
  
  var str = String(val).trim().replace(/^[Rr][Pp]\s*/, '').replace(/\s/g, '');
  
  if (str.indexOf('.') !== -1 && str.indexOf(',') !== -1) {
    if (str.lastIndexOf(',') > str.lastIndexOf('.')) {
      str = str.replace(/\./g, '').replace(',', '.'); 
    } else {
      str = str.replace(/,/g, '');
    }
  } else if (str.indexOf(',') !== -1) {
    var parts = str.split(',');
    if (parts.length > 2 || parts[1].length === 3) {
      str = str.replace(/,/g, '');
    } else {
      str = str.replace(',', '.');
    }
  } else if (str.indexOf('.') !== -1) {
    var parts = str.split('.');
    if (parts.length > 2 || parts[1].length === 3) {
      str = str.replace(/\./g, '');
    }
  }
  return parseFloat(str) || 0;
}

function filterByRole(data, role, wkAccess) {
  if (!data || data.length === 0) return [];
  if (!role || !wkAccess) return data; 
  if (role === 'ADMIN' || wkAccess === 'ALL') return data;
  const allowed = String(wkAccess).split(',').map(s => s.trim());
  return data.filter(item => allowed.includes(item.WK));
}

/**
 * REUSABLE SECURITY LAYER: Validasi Kredensial Langsung di Sisi Server
 */
function verifyServerSideRole(username) {
  if (!username) return { active: false };
  try {
    const ss = SpreadsheetApp.getActiveSpreadsheet();
    const sheet = ss.getSheetByName('MASTER_USER');
    const data = sheet.getDataRange().getValues();
    for (let i = 1; i < data.length; i++) {
      if (String(data[i][0]).toLowerCase() === String(username).trim().toLowerCase()) {
        return { 
          active: true, 
          user: { username: data[i][0], nama: data[i][2], role: data[i][3], wkAccess: data[i][4] }
        };
      }
    }
  } catch (e) {
    if (SpreadsheetApp.getActiveSpreadsheet().getSheetByName('LOG_ACTIVITY')) {
      SpreadsheetApp.getActiveSpreadsheet().getSheetByName('LOG_ACTIVITY').appendRow([new Date(), "SYSTEM", "ERROR_AUTH", e.toString()]);
    }
  }
  return { active: false };
}

function updateUserProfile(form) {
  try {
    const ss = SpreadsheetApp.getActiveSpreadsheet();
    const sheet = ss.getSheetByName('MASTER_USER');
    const data = sheet.getDataRange().getValues();
    for (let i = 1; i < data.length; i++) {
      if (String(data[i][0]) === String(form.username)) {
        sheet.getRange(i + 1, 3).setValue(form.nama);
        if (form.password) sheet.getRange(i + 1, 2).setValue(computeSHA256(form.password));
        return { success: true, newName: form.nama };
      }
    }
    return { success: false, message: "User tidak ditemukan" };
  } catch (e) { return { success: false, message: e.toString() }; }
}

function sendBudgetSummaryReport() {
  if (!EMAIL_RECIPIENTS) return;
  const ss = SpreadsheetApp.getActiveSpreadsheet();
  const today = new Date();
  const month = today.getMonth(); 
  
  const allRealisasi = [
    ...cleanData(ss.getSheetByName('TRANSAKSI_REALISASI').getDataRange().getValues()),
    ...cleanData(ss.getSheetByName('TRANSAKSI_INVOICE_BUJP').getDataRange().getValues()),
    ...cleanData(ss.getSheetByName('TRANSAKSI_STAKEHOLDER').getDataRange().getValues())
  ];
  const paguData = cleanData(ss.getSheetByName('MASTER_ANGGARAN').getDataRange().getValues());
  
  let reportTitle = "";
  let periodText = "";
  let filteredData = [];
  
  if (month === 6) { 
    reportTitle = "Summary Anggaran Semester I (Januari - Juni)";
    periodText = "Januari - Juni";
    filteredData = allRealisasi.filter(d => {
      var dateObj = new Date(d.Tanggal);
      return !isNaN(dateObj.getTime()) && dateObj.getMonth() <= 5;
    });
  } else if (month === 0) { 
    reportTitle = "Summary Anggaran Semester II & Tahunan";
    periodText = "Juli - Desember";
    filteredData = allRealisasi.filter(d => {
      var dateObj = new Date(d.Tanggal);
      return !isNaN(dateObj.getTime()) && dateObj.getMonth() >= 6;
    });
  } else { return; }

  // STATE LOCK SERVICE: Cegah duplikasi pengiriman email ganda
  const props = PropertiesService.getScriptProperties();
  const lockKey = "LAST_REPORT_YEAR_MONTH_" + today.getFullYear() + "_" + month;
  if (props.getProperty(lockKey) === "SENT") return;

  const totalRealisasiPeriode = filteredData.reduce((a, b) => a + parseSheetNumber(b.Jumlah), 0);
  
  const categoryMap = {};
  filteredData.forEach(d => {
    categoryMap[d.Pilihan_Anggaran] = (categoryMap[d.Pilihan_Anggaran] || 0) + parseSheetNumber(d.Jumlah);
  });
  
  const categories = Object.keys(categoryMap);
  const topCategory = categories.length > 0 ? categories.reduce((a, b) => categoryMap[a] > categoryMap[b] ? a : b) : "N/A";
  const proyeksiTahunDepan = month === 6 ? totalRealisasiPeriode * 2 : totalRealisasiPeriode;

  const htmlBody = `
    <div style="font-family: sans-serif; color: #1e293b;">
      <h2 style="color: #064e3b; border-bottom: 2px solid #10b981; padding-bottom: 10px;">${reportTitle}</h2>
      <p>Berikut analisa penggunaan anggaran Divisi Sekuriti:</p>
      <table style="width: 100%; margin-bottom: 20px;">
        <tr><td><b>Periode</b></td><td>: ${periodText}</td></tr>
        <tr><td><b>Total Penyerapan</b></td><td>: Rp ${totalRealisasiPeriode.toLocaleString('id-ID')}</td></tr>
        <tr><td><b>Item Terbesar</b></td><td>: ${topCategory}</td></tr>
      </table>
      <div style="background: #f1f5f9; padding: 15px; border-left: 4px solid #10b981;">
        <h4 style="margin: 0 0 10px 0;">Proyeksi Rapat Anggaran:</h4>
        <p style="margin: 0;">Estimasi kebutuhan tahun depan: <b>Rp ${proyeksiTahunDepan.toLocaleString('id-ID')}</b></p>
        <small>*Dihitung berdasarkan tren penyerapan periode berjalan.</small>
      </div>
      <br><a href="${APP_LINK}" style="color: #10b981; font-weight: bold; text-decoration: none;">>>> KLIK DISINI UNTUK DETAIL DASHBOARD</a>
    </div>`;

  MailApp.sendEmail({ to: EMAIL_RECIPIENTS, subject: `[REPORT] ${reportTitle}`, htmlBody: htmlBody });
  
  props.setProperty(lockKey, "SENT");
  ss.getSheetByName('LOG_ACTIVITY').appendRow([new Date(), "SYSTEM_CRON", "Report Dispatched", "Key logged: " + lockKey]);
}

function checkContractExpirations() {
  if (!EMAIL_RECIPIENTS) return;
  const ss = SpreadsheetApp.getActiveSpreadsheet();
  const wkData = cleanData(ss.getSheetByName('MASTER_WILAYAH_KERJA').getDataRange().getValues());
  const today = new Date();
  let alertList = "";

  wkData.forEach(wk => {
    const endDate = new Date(wk.CONTRACT_END_DATE);
    const diffTime = endDate - today;
    const diffMonths = Math.ceil(diffTime / (1000 * 60 * 60 * 24 * 30.44));

    if (diffMonths >= 1 && diffMonths <= 3) {
      alertList += `<li><b>${wk.Nama_WK}</b> (${wk.BUJP_NAME}) - Sisa <b>${diffMonths} Bulan</b></li>`;
    }
  });

  if (alertList !== "") {
    const htmlBody = `<div style="font-family: sans-serif;"><h3 style="color: #b91c1c;">⚠️ Reminder Kontrak Berakhir</h3><ul>${alertList}</ul><br><a href="${APP_LINK}">KLIK DISINI</a></div>`;
    MailApp.sendEmail({ to: EMAIL_RECIPIENTS, subject: "[ALERT] Reminder Kontrak BUJP", htmlBody: htmlBody });
  }
}

function sendMonthlyEvidenceAudit() {
  if (!EMAIL_RECIPIENTS) return;
  const ss = SpreadsheetApp.getActiveSpreadsheet();
  const today = new Date();
  const currentMonth = today.getMonth();
  const sheetsToAudit = ['TRANSAKSI_REALISASI', 'TRANSAKSI_INVOICE_BUJP', 'TRANSAKSI_STAKEHOLDER'];
  let missingList = "";

  sheetsToAudit.forEach(name => {
    const data = cleanData(ss.getSheetByName(name).getDataRange().getValues());
    const missing = data.filter(d => {
      var dateObj = new Date(d.Tanggal);
      return !isNaN(dateObj.getTime()) && dateObj.getMonth() === currentMonth && !d.Evidence;
    });
    if (missing.length > 0) missingList += `<li><b>${name}:</b> ${missing.length} Transaksi tanpa bukti.</li>`;
  });

  if (missingList !== "") {
    const htmlBody = `<div style="font-family: sans-serif;"><h3 style="color: #e11d48;">Audit Evidence Bulanan</h3><ul>${missingList}</ul><br><a href="${APP_LINK}">KLIK DISINI</a></div>`;
    MailApp.sendEmail({ to: EMAIL_RECIPIENTS, subject: "[AUDIT] Evidence Belum Lengkap", htmlBody: htmlBody });
  }
}
